### PR TITLE
HD-1622 - Add feature, improvement branches to trigger CI

### PR DESCRIPTION
**Pull request by lavigne958**

### CODE REVIEW

**Comment by lavigne958** [comment]
@tcarmet  in order to pass PR #226 and the next one to actually make the release, we must pass this PR first.

**Review by tcarmet — APPROVED** [review]

**Comment by tcarmet** [comment]
> @tcarmet in order to pass PR #226 and the next one to actually make the release, we must pass this PR first.

perfect, thanks I'll rebase once this one is merged

**Review by lunatikub — APPROVED** [review]

**Pull request merged**
