### PR TITLE
Dev/ft/ring 28696 regex replication

### PR DESCRIPTION
**Pull request by maximelubin**
Idea is to be able to select code to use (replication/erasure, number of parts) given a <bucket>/<object> pattern

### CODE REVIEW

**Review by xroche-scality — APPROVED** [review]

**Review by xroche-scality — COMMENTED** [review]
Minor: typo in commit

**Review by xroche-scality — APPROVED** [review]
Minor: typo in commit

**Review by xroche-scality — APPROVED** [review]

**Review by xroche-scality — APPROVED** [review]
Food for thought: is there any documentation on which "pattern" is used ? Regexp are a unholy mess, and I have no idea of the exact syntax for nodejs (regarding pipe operators, etc.)

**Review by xroche-scality — APPROVED** [review]
Is 412 code standard in S3 for this case ? Looks a bit abusing HTTP (412 is supposed to be reserved for headers preconditions only afaics)

**Review by xroche-scality — APPROVED** [review]
Un peu mal au crâne là

**Review by xroche-scality — APPROVED** [review]

**Comment by maximelubin** [comment]
> Is 412 code standard in S3 for this case ? Looks a bit abusing HTTP (412 is supposed to be reserved for headers preconditions only afaics)

I have no idea. But I thought 412 fitted nicely with the problem. I am open to suggestion though

**Comment by maximelubin** [comment]
As discussed, swithcing from 412 to a 422 (unprocessable entiy). Stretching webdav spec but still better than 412.

**Pull request merged**
